# -*- coding: utf-8 -*-
"""generate.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nmu40nIM7RDLIBDz7TcEAmjSOQ6TJmgz
"""

import pyrosim.pyrosim as pyrosim

#generate.py
#Create World function in generate.py
def Create_World():
  pyrosim.Start_SDF("object.sdf")
  pyrosim.End()



#Generate body function
def Generate_Body():
  #vertical_offset = 1.0
  pyrosim.Start_URDF("body.urdf")
  pyrosim.Send_Cube(name="Torso", pos=[1.5, 0, 1.5], size=[width, length, height])
  pyrosim.Send_Joint( name = "Torso_BackLeg" , parent= "Torso" , child = "BackLeg" , type = "revolute", position = [1.0,0,1.0])
  pyrosim.Send_Cube(name="BackLeg", pos=[-0.5, 0, -0.5], size=[width, length, height])
  pyrosim.Send_Joint(name = "Torso_FrontLeg" , parent= "Torso" , child = "FrontLeg" , type = "revolute", position = [2.0,0,1.0])
  pyrosim.Send_Cube(name="FrontLeg", pos=[0.5, 0, -0.5], size=[width, length, height])
  pyrosim.End()



#Create Robot function in generate.py
def Create_Robot():
  Generate_Body()


def Generate_Brain():
  pyrosim.Start_NeuralNetwork("brain.nndf")
  #Sensor Neurons
  pyrosim.Send_Sensor_Neuron(name=0, linkName="Torso")
  pyrosim.Send_Sensor_Neuron(name=1, linkName="BackLeg")
  pyrosim.Send_Sensor_Neuron(name=2, linkName="FrontLeg")
  #Motor Neurons
  pyrosim.Send_Motor_Neuron(name=3, jointName="Torso_BackLeg")
  pyrosim.Send_Motor_Neuron(name=4, jointName="Torso_FrontLeg")
    
  # Motor Neuron 3 (Back Leg):
  pyrosim.Send_Synapse(sourceNeuronName=0, targetNeuronName=3, weight=-0.3)
  pyrosim.Send_Synapse(sourceNeuronName=1, targetNeuronName=3, weight=0.5)
  pyrosim.Send_Synapse(sourceNeuronName=2, targetNeuronName=3, weight=-1.0)
    
  # Motor Neuron 4 (Front Leg):
  pyrosim.Send_Synapse(sourceNeuronName=0, targetNeuronName=4, weight=-0.6)
  pyrosim.Send_Synapse(sourceNeuronName=2, targetNeuronName=4, weight=-0.25)  
  pyrosim.End()
  

length = 1.0
width = 1.0
height = 1.0

Create_World()
Create_Robot()
Generate_Brain()