# -*- coding: utf-8 -*-
"""generate.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nmu40nIM7RDLIBDz7TcEAmjSOQ6TJmgz
"""

from numpy import random
import pyrosim.pyrosim as pyrosim

#generate.py
#Create World function in generate.py
def Create_World():
  pyrosim.Start_SDF("object.sdf")
  pyrosim.End()



#Generate body function
def Generate_Body():
  #vertical_offset = 1.0
  pyrosim.Start_URDF("body.urdf")
  pyrosim.Send_Cube(name="Torso", pos=[1.5, 0, 1.5], size=[width, length, height])
  pyrosim.Send_Joint( name = "Torso_BackLeg" , parent= "Torso" , child = "BackLeg" , type = "revolute", position = [1.0,0,1.0])
  pyrosim.Send_Cube(name="BackLeg", pos=[-0.5, 0, -0.5], size=[width, length, height])
  pyrosim.Send_Joint(name = "Torso_FrontLeg" , parent= "Torso" , child = "FrontLeg" , type = "revolute", position = [2.0,0,1.0])
  pyrosim.Send_Cube(name="FrontLeg", pos=[0.5, 0, -0.5], size=[width, length, height])
  pyrosim.End()



#Create Robot function in generate.py
def Create_Robot():
  Generate_Body()


def Generate_Brain():
  pyrosim.Start_NeuralNetwork("brain.nndf")
  # Define sensor neuron names and their corresponding link names
  sensor_neurons = {0: "Torso", 1: "BackLeg", 2: "FrontLeg"}
  for s in sensor_neurons:
      pyrosim.Send_Sensor_Neuron(name=s, linkName=sensor_neurons[s])
    
  # --- Create Motor Neurons ---
  # Define motor neuron names and their corresponding joint names
  motor_neurons = {3: "Torso_BackLeg", 4: "Torso_FrontLeg"}
  for m in motor_neurons:
      pyrosim.Send_Motor_Neuron(name=m, jointName=motor_neurons[m])
    
  # --- Create Fully Connected Synapses ---
  # For each sensor neuron and each motor neuron, create a synapse with a random weight in [-1,1]
  for s in sensor_neurons:
      for m in motor_neurons:
          # Generate a random weight in the range [-1, 1]
          weight = random.uniform(-1, 1)
          pyrosim.Send_Synapse(sourceNeuronName=s, targetNeuronName=m, weight=weight)
    
  pyrosim.End()
  

length = 1.0
width = 1.0
height = 1.0

Create_World()
Create_Robot()
Generate_Brain()