# -*- coding: utf-8 -*-
"""motor.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x6ruemFyIZjYmjhxb9RXwOgfCrnp6Zhs
"""

#import statements
import pybullet as p
import pybullet_data
import pyrosim.pyrosim as pyrosim
import numpy as np
import constants_py as c

#from robot_py import ROBOT


#motor.py
class MOTOR:

  def __init__(self, jointName):

      # Save the joint name in the instance.
      self.jointName = jointName
      # Prepare the motor (its control vector and parameters).
      self.Prepare_To_Act()

  def Prepare_To_Act(self):

      # Set the motor's amplitude, frequency, and phase offset.
      self.amplitude = c.backAmplitude
      self.frequency = c.backFrequency
      self.offset = c.backPhaseOffset


      # Modify the frequency for one motor based on its joint name.
      # For example, if the joint is "Torso_BackLeg", let it oscillate at half the frequency.
      if self.jointName == b"Torso_BackLeg":
          freq = self.frequency / 2.0
      else:
          freq = self.frequency

      # Create a vector for storing motor command values.
      self.motorValues = np.zeros(c.iterations)
      # Compute motor command values for every time step.
      for t in range(c.iterations):
          self.motorValues[t] = self.amplitude * np.sin(
              freq * (2 * np.pi * t / (c.iterations - 1)) + self.offset
          )


  def Set_Value(self, robot, desiredAngle):
      # Send the motor command to the joint associated with this motor.
      pyrosim.Set_Motor_For_Joint(
          bodyIndex=robot.robotId,
          jointName=self.jointName,
          controlMode=p.POSITION_CONTROL,
          targetPosition=desiredAngle,
          maxForce=100
      )


  def Save_Values(self):
      # Save the motor values vector to a file.
      np.save("motor_" + self.jointName + ".npy", self.motorValues)