# -*- coding: utf-8 -*-
"""run.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bn6J7r7rdyy4AEIYGn36QiRQqOcUzDFQ
"""

#This file runs all the python files, contains terminal commands
!pip install pybullet
!pip install imageio-ffmpeg

!git clone https://github.com/jbongard/pyrosim.git

!pip install matplotlib

#Command to install constants library
!pip install constants

#Running search.py to use random synaptic weights for the robots
!python search_py.py

#Running generate.py before simulate to ensure object.SDF is there
!python generate_py.py

#command to run simulation to run simulate.py
!python simulate_py.py DIRECT 0

#Display Video
from IPython.display import HTML
from base64 import b64encode

def display_video(filename):
    with open(filename,'rb') as f:
        mp4 = f.read()
    data_url = "data:video/mp4;base64," + b64encode(mp4).decode()
    return HTML(f'<video width="480" controls><source src="{data_url}" type="video/mp4"></video>')

display_video("best_vid.mp4")

